name: Release

on:
  push:
    tags:
      - "*"
env:
  PYPI_PROJECT_NAME: flomo
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{env.PYPI_PROJECT_NAME}}
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build package
        run: python setup.py sdist bdist_wheel

      #   - name: Publish package distributions to PyPI
      #     uses: pypa/gh-action-pypi-publish@release/v1
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          twine upload dist/*
